import type { ExportPackage } from "@/lib/export";

// A real, syntactically valid .nk text template - Nuke reads its scripts as
// plain text (a Tcl-ish node graph), so this doesn't need a Nuke license or
// the Nuke Python API to produce, per the product's explicit non-goal: "no
// full Nuke automation, the export step writes a .nk script as a text
// template." Read plate -> Read gen -> Merge -> OCIOColorSpace -> Grain ->
// Write, matching docs/ARCHITECTURE.md section 9.
export function generateNukeScript(pkg: ExportPackage): string {
  const shotCode = pkg.shot.code;
  const version = pkg.approvedVersion;
  const genFile = version
    ? `gen/${shotCode}_gen_v${String(version.versionNumber).padStart(3, "0")}.mov`
    : `gen/${shotCode}_gen_MISSING.mov`;
  const plateFile = `plate/${shotCode}_plate.####.exr`;
  const writeFile = `render/${shotCode}_comp.####.exr`;

  // null = "omit this line entirely" (conditional content that doesn't
  // apply); "" = a deliberate blank line kept in the output as a spacer.
  const lines: (string | null)[] = [
    `# ${shotCode} - generated by Dailies, ${new Date().toISOString()}`,
    `# Sequence: ${pkg.sequence.code} (${pkg.show.name})`,
    `# Approved version: ${version ? `v${version.versionNumber}` : "none - no approved version yet, this script is a template only"}`,
    version ? `# Prompt: ${version.generationPrompt.replace(/\n/g, " ").slice(0, 300)}` : null,
    pkg.shot.screenDirection ? `# Screen direction: ${pkg.shot.screenDirection}` : null,
    "",
    "Root {",
    ` name ${shotCode}_comp.nk`,
    ` format "1280 720 0 0 1280 720 1 HD_720"`,
    ` fps 24`,
    "}",
    "",
    "Read {",
    " inputs 0",
    ` file ${plateFile}`,
    " # No live-action plate has been ingested for this shot - Dailies is a",
    " # pure-generative pipeline today. This Read is a placeholder for a",
    " # future workflow where a real plate exists to composite against.",
    ` name Read_Plate_${shotCode}`,
    "}",
    "",
    "Read {",
    " inputs 0",
    ` file ${genFile}`,
    version && !version.hasVideoBytes
      ? " # WARNING: no video bytes are actually stored for this version."
      : null,
    ` name Read_Gen_${shotCode}`,
    "}",
    "",
    "OCIOColorSpace {",
    " inputs 1",
    ' in_colorspace "sRGB"',
    ' out_colorspace "scene_linear"',
    ` name OCIO_${shotCode}`,
    "}",
    "",
    "Merge2 {",
    " inputs 2",
    " operation over",
    ` name Merge_${shotCode}`,
    "}",
    "",
    "Grain {",
    " size 0.4",
    " irediance 0.02",
    ` name Grain_${shotCode}`,
    "}",
    "",
    "Write {",
    ` file ${writeFile}`,
    " file_type exr",
    ' colorspace "scene_linear"',
    ` name Write_${shotCode}`,
    "}",
    "",
  ];

  return lines.filter((line): line is string => line !== null).join("\n") + "\n";
}
